<a href="https://colab.research.google.com/github/NiyazovIlia/Python-Data-Science/blob/lesson-2/GB_lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

**Задание 1**

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,3,1],
               [6,8,11,10,7]])
b = a.T
mean_a = a.T.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание 2**

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [ ]:
a_centered = np.subtract(b, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
a1 = a_centered[:, 0]
a2 = a_centered[:, 1]
a_centered_sp = np.dot(a1,a2)
a_centered_sp
c = a_centered_sp/(a_centered.shape[0] -1)
c

2.0

**Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [ ]:
np.cov(b.T)

array([[1. , 2. ],
       [2. , 4.3]])

**Задание 5**

Создайте одномерный массив z случайных равномерно распределенных целых чисел от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.


In [ ]:
z = np.random.uniform(-50,50, 8)
z_ind = np.array(z > 0)
print(z)
z[z_ind]

[-25.67342519 -39.97168218  43.74846798  -5.08898634 -49.34225273
   0.45909935  48.8987064   -0.655076  ]


array([43.74846798,  0.45909935, 48.8987064 ])

**Задание 6**

Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)

Найдите среднее значение и стандартное отклонение по каждому признаку.

Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.

Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.

Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)


In [ ]:
X = np.random.randint(0, 255, (10,5))
# среднее значение
x_str = X.mean(axis=0)
# стандартное отклонение
x_std = X.std(axis=0)
# новый массив
X_standart = np.subtract(X, x_str)/x_std
X_standart_str = X_standart.mean(axis=0)
X_standart_std = X_standart.std(axis=0)
X, X_standart, X_standart_str, X_standart_std

(array([[242,  57, 182,  92,  32],
        [226,   2, 225,  16, 157],
        [114, 205,  63, 134, 180],
        [ 10, 140, 214,  87, 140],
        [ 90, 168,  86, 130, 233],
        [157,  52, 193, 227, 143],
        [140,  84, 229, 127,  11],
        [208,  32, 133,  23, 223],
        [209, 150,  53,  50, 144],
        [  4, 103, 190, 162,  59]]),
 array([[ 1.2550959 , -0.68270132,  0.39195699, -0.20697564, -1.3934203 ],
        [ 1.05821811, -1.57037444,  1.0607725 , -1.43589349,  0.34487848],
        [-0.31992641,  1.70594634, -1.45895103,  0.47216317,  0.66472545],
        [-1.59963203,  0.65687811,  0.88968016, -0.2878255 ,  0.10846984],
        [-0.61524309,  1.10878442, -1.10121251,  0.40748329,  1.40176413],
        [ 0.20918265, -0.76339888,  0.56304933,  1.97597055,  0.15018901],
        [ 0.        , -0.24693452,  1.12298789,  0.35897337, -1.68545449],
        [ 0.8367306 , -1.08618911, -0.37018161, -1.32270369,  1.26270023],
        [ 0.84903546,  0.81827322, -1.61448952, 

**Задание 7**

Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.

Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)

Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

In [ ]:
arrra_1 = np.random.randint(0, 1000, 512)
arrra_2 = np.random.randint(0, 1000, 512)
# вычитаение массивов
sub = np.subtract(arrra_1, arrra_2)
# возведение в степень
sub_2 = np.power(sub, 2)
# суммирование и квадатный корень
sub_2_sum = np.sqrt(np.sum(sub_2))
sub_2_sum,np.linalg.norm(arrra_1), np.linalg.norm(arrra_2)

(9520.099579311132, 12834.946474372226, 12943.500647042902)

**Задание 8**

Используйте ранее созданный массив X.

Найдите минимальное значение и максимальное по каждому признаку.

Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.

Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.

Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)


In [ ]:
X = np.random.randint(0, 255, (10,5))
# минимальное значение "вдоль" строк
x_min_1 = np.min(X, axis=0)
# максимальное значение "вдоль" строк
x_max_1 = np.max(X, axis=0)
# новый массив
X_norm = np.subtract(X, x_min_1)/(x_max_1 - x_min_1)
X_norm

array([[0.32240437, 0.09777778, 1.        , 0.54411765, 0.12446352],
       [0.89617486, 0.04888889, 0.02234637, 0.93627451, 0.527897  ],
       [0.0273224 , 0.8       , 0.76536313, 0.58823529, 0.7639485 ],
       [0.31693989, 0.        , 0.96648045, 0.49019608, 0.39914163],
       [0.86338798, 0.34666667, 0.52513966, 0.        , 0.34763948],
       [0.07650273, 0.39555556, 0.05027933, 1.        , 0.60515021],
       [0.        , 0.52888889, 0.56424581, 0.83823529, 1.        ],
       [0.08196721, 0.30222222, 0.67039106, 0.23039216, 0.        ],
       [0.42622951, 0.48444444, 0.51955307, 0.92156863, 0.87124464],
       [1.        , 1.        , 0.        , 0.03921569, 0.73819742]])

**Pandas**

**Задание 1**

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],

[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd

In [ ]:
authors = pd.DataFrame({'author_id':[1,2,3], 
                       'author_name': ['Тургенев', 'Чехов', 'Островский']})
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})

**Задание 2**

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [ ]:
authors_price = pd.merge(authors, book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [ ]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

**Задание 4**

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:

author_name, min_price, max_price и mean_price,

в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
authors_stat = authors_price.groupby('author_name')
a1 = authors_stat.agg({"price": "min"}).rename(columns={'price':'min_price'})
a2 = authors_stat.agg({"price": "max"}).rename(columns={'price':'max_price'})
a3 = authors_stat.agg({"price": "mean"}).rename(columns={'price':'mean_price'})
authors_stat = pd.concat([a1,a2,a3], axis=1)
print(authors_stat)

             min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000


**Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [ ]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover',aggfunc=np.sum, fill_value=0)

book_info.to_pickle('book_info.pkl')

book_info2 = pd.read_pickle('book_info.pkl')

print(book_info)

print(book_info2)

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950
cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950


**Задание 6**

В этом задании будем работать с датасетом, в котором представлены данные по сериалам и фильмам на Netflix (Netflix Movies and TV Shows).

Ознакомьтесь с описанием данных и скачайте датасет netflix_titles.csv с сайта Kaggle.com https://www.kaggle.com/shivamb/netflix-shows

Считайте датасет. Посмотрите, сколько наблюдений и сколько признаков есть в этом наборе данных.

Посчитайте, как много сериалов и фильмов представлено в этом датасете.

Посчитайте, как много пропущенных значений (NaN) есть в признаках director и country.

Посчитайте, сколько фильмов выпустили раньше 2003 года.

Посчитайте, какая страна чаще всего выпускает фильмы на Netflix.


In [ ]:
netflix = pd.read_csv('netflix_titles.csv')

netflix['type'].value_counts()

n = netflix[{'director', 'country'}].isnull()

n.value_counts()

netflix.head()

netflix.loc[netflix['release_year'] < 2003]

netflix.value_counts('country')

country
United States                              2555
India                                       923
United Kingdom                              397
Japan                                       226
South Korea                                 183
                                           ... 
Spain, United Kingdom, United States          1
Spain, Thailand, United States                1
Spain, Switzerland                            1
Spain, Portugal                               1
Norway, United Kingdom, France, Ireland       1
Length: 681, dtype: int64

**Задание 7**

В этом датасете есть признак date_added (дата добавления сериала/фильма на платформу), на основе этого признака создайте три новых: year_added - год добавления, month_added - месяц добавления и day_added - день добавления.


In [ ]:
n = pd.to_datetime(netflix['date_added'])
year = []
month = []
day = []

for i in n.index:
  year.append(n[i].year)
  month.append(n[i].month)
  day.append(n[i].day)

new = pd.DataFrame({'year_added': year, 'month_added': month, 'day_added': day}, dtype=np.int32)
netflix_new = pd.concat([netflix, new], axis=1)
netflix_new.head()

show_id     type  title  ... year_added month_added day_added
0      s1  TV Show     3%  ...       2020           8        14
1      s2    Movie   7:19  ...       2016          12        23
2      s3    Movie  23:59  ...       2018          12        20
3      s4    Movie      9  ...       2017          11        16
4      s5    Movie     21  ...       2020           1         1

[5 rows x 15 columns]

**Задание 8**

Выберите только наблюдения, где страна 'United States', 'India' или 'United Kingdom'

Для каждой страны посчитайте общее количество фильмов и сериалов по месяцам выпуска. Столбцы нового сводного датафрейма должны называться, как месяца в признаке month_added, а индексов будет два: страна и тип.


In [ ]:
netflix_country = netflix_new.loc[(netflix_new['country'] == 'United States') | (netflix_new['country'] == 'India' ) |  (netflix_new['country'] == 'United Kingdom' ), 'country']
netflix_type = netflix_new.loc[(netflix_new['country'] == 'United States') | (netflix_new['country'] == 'India' ) |  (netflix_new['country'] == 'United Kingdom' ), 'type']

netflix_test = pd.pivot_table(netflix_new, values='type', index=[netflix_country, netflix_type], columns='month_added', aggfunc=np.count_nonzero)

netflix_test




month_added              1    2    3    4    5   ...   8    9    10   11   12
country        type                              ...                         
India          Movie     65   45   83   72   65  ...   70   55   97   87  104
               TV Show    2    2   12   14    5  ...    4    1    8    3    6
United Kingdom Movie     17   16   20   12   18  ...   18   16   22    8   25
               TV Show   13   17   34   14   10  ...   22   19   22    9   20
United States  Movie    245  118  156  139  109  ...  143  128  172  210  174
               TV Show   61   45   49   47   46  ...   55   81   68   69   80

[6 rows x 12 columns]